### PR TITLE
First semi-stable implementation

### PR DESCRIPTION
**Pull request by jmknight2**
While not complete, this version of the project is at a stage where almost all the pieces are in place. It's worthwhile to go ahead and update the Master branch

### CODE REVIEW

**Review by zachMitchell — COMMENTED** [review]
There are a couple of things:
1. quaggajs seems to have stopped working, I'm investigating on this right now... (There's an error on line 34 on scanner.js)

2.I'd like to make one last change to scramblerVerify before this is pushed that allows removing scrambled text from an external file if that's alright with you guys

**Review by mwratliff — APPROVED** [review]
Looks good to me after testing to make sure it works on the AWS server.

**Comment by zachMitchell** [comment]
Ok, everything should be good to go 😌 
The problem with the barcode scanner was on my end; I didn't test with a proper barcode XP

But I'm finished making changes if we want to make the big merge

**Review by zachMitchell — APPROVED** [review]
Ok, everything should be good to go 😌 
The problem with the barcode scanner was on my end; I didn't test with a proper barcode XP

But I'm finished making changes if we want to make the big merge

**Pull request merged**
